name: Test and Comment
pandas
pandas==2.2.2
import pandas as pd
from sklearn.linear_model import LogisticRegression
import pandas as pd
import pandas as pd
pandas==2.2.2
name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest and Save Output
        run: |
          pytest --junitxml=results.xml > results.txt

      - name: Publish Report with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Test Results" > report.md
          cat results.txt >> report.md
          cml comment create report.md

